setup: unlink target file before rename
On Windows we get an error when using rename to overwrite an existing
file:

FileExistsError: [WinError 183] Cannot create a file when that file
 already exists: 'charmcraft\\version.py~' -> 'charmcraft\\version.py'

Unlink the target first if it exists.

Signed-off-by: Chris Patterson <chris.patterson@canonical.com>